name: CI

# Déclenche le workflow pour chaque pr
on:
  pull_request:

jobs:
  # --- JOB App ---
  app:
    name: App CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: application-assistance-guidage
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installer les dependances
        run: |
          npm install
          npx expo install @expo/metro-runtime
          npx expo install expo-router

      - name: Lint code
        run: npm run lint

      - name: Check Expo project
        run: npx expo doctor
